server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: openApiRoute
          uri:
            http://localhost:8001
          predicates:
            - Path=/api/**
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

